kickreason: Scheduled Shutdown.
warntimes: 900,600,300,240,180,120,60,45,30,20,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1
gracetime: 20
kickonshutdown: true
shutdowntimes: 3:00
shutdownmessage: Server is shutting down